server:
  port: 9888

spring:
  application:
    name: WindyMaster

eureka:
  server:
    # server清理无效节点的时间间隔
    eviction-interval-timer-in-ms: 10
    # 是否开启自我保护，默认true
    enable-self-preservation: true
    # 开启自我保护的系数
    renewal-percent-threshold: 0.85
    # 一级缓存与二级缓存同步时间
    response-cache-update-interval-ms: 0
    # 关闭服务端一级cache缓存
    use-read-only-response-cache: false
  instance:
    # 服务时效时间，默认90秒.当server 30秒内没有收到client的注册信息时，会将该节点剔除
    lease-expiration-duration-in-seconds: 30
    # 服务续约任务调用间隔时间，默认30秒.client每隔30秒向server上报自己状态，避免被server剔除
    lease-renewal-interval-in-seconds: 10
    # 注册服务时是否使用IP注册，默认false
    prefer-ip-address: true

  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://windy-cluster:9888/eureka/

logging:
  level:
    com.netflix: warn