server:
  port: 8070

spring:
  application:
    name: WindyClient

eureka:
  client:
    # 是否注册
    register-with-eureka: true
    # 是否检索服务
    fetch-registry: true
    # 连接server服务器超时时间
    eureka-server-connect-timeout-seconds: 5
    # 连接server的连接空闲时长
    eureka-connection-idle-timeout-seconds: 30
    # 连接server读取数据超时时间
    eureka-server-read-timeout-seconds: 8
    # 连接server的最大连接数
    eureka-server-total-connections: 200
    # 对单个server的最大连接数
    eureka-server-total-connections-per-host: 50
    # 获取集群中最新的server节点数据
    eureka-service-url-poll-interval-seconds: 15
    # client维持与server的心跳线程数
    heartbeat-executor-thread-pool-size: 2
    # client本地缓存清单更新间隔，默认30秒.
    # client每隔30秒，向server请求可用服务清单。对于API网关类应用，可以适当降低时间间隔
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: ${eureka_zone}



